#!/bin/bash

#SBATCH --job-name=roi_rsa
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --error=slurm-%A_%a.err
#SBATCH --output=slurm-%A_%a.out
#SBATCH --mail-type=end
#SBATCH --mail-user=rapalsul@uci.edu

source ~/.bashrc
conda activate mvpa_env

for sub_id in $(cat sublist_initials.txt); do
    number=${sub_id%%_*}
    echo "Running subject $SUBJECT"

    python PS_rsa.py $number fsROIS
done
