#!/bin/bash

#SBATCH --job-name=smoothing
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --error=slurm-%A_%a.err
#SBATCH --output=slurm-%A_%a.out
#SBATCH --mail-type=end
#SBATCH --mail-user=rapalsul@uci.edu
#SBATCH --mem=32G

source ~/.bashrc
conda activate base
module load fsl/6.0.4

cd /share/crsp/lab/bornstea/share/R01-Analysis/ISC

./smooth_prepost.sh combined_prepost/raw/ combined_prepost/smoothed/ 4
