#!/bin/bash
#SBATCH --job-name=smoothing
#SBATCH -A bornstea_lab
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-type=end
#SBATCH --mail-user=rapalsul@uci.edu
#SBATCH --mem=16G
#SBATCH --array=1
SUBJECT_ID=$(sed -n "$((SLURM_ARRAY_TASK_ID))p" sublist.txt)

FMRIPREP_DIR="../../R01-fmri/fmriprep_pepolar/sub-${SUBJECT_ID}/ses-3/func/"
OUTPUT_DIR="./smoothed_func/sub-${SUBJECT_ID}/"
FWHM=6

echo "Smoothing subject: ${SUBJECT_ID}"

./smooth_glm.sh "$FMRIPREP_DIR" "$OUTPUT_DIR" "$FWHM"
